[package]
name = "paczkomat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.1"
local-ip-address = "0.6.1"
reqwest = { version = "0.12", features = ["json"] }
dotenv = "0.15.0"
