# Generated by Django 5.0.1 on 2024-06-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='id',
        ),
        migrations.AddField(
            model_name='locker',
            name='gpio',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locker',
            name='locker_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
