# Generated by Django 5.0.1 on 2024-06-21 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paczkomat',
            name='port',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(8001), django.core.validators.MaxValueValidator(9000)]),
        ),
        migrations.AlterField(
            model_name='paczkomat',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
