# Generated by Django 5.0.1 on 2024-08-07 14:15

import backend_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_remove_locker_id_locker_gpio_alter_locker_locker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_code',
            field=models.IntegerField(default=backend_app.utils.get_package_safe_code, editable=False),
        ),
    ]
